name: 'VoidPointerFramework'
description: ${project.description}
website: ${project.url}

author: 'VoidPointer aka NyanGuyMF'
version: ${project.version}

main: voidpointer.bukkit.framework.${project.name}Plugin
